x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  clusterConstraints:
    k8sVersion: ">=1.18.0"
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: True

  images:
    '':  # Primary image has no name.
      properties:
        image:
          type: FULL
    citrix-adc-metrics-exporter:
      properties:
        exporter.image:
          type: FULL
  deployerServiceAccount:
    description: "Creates app resources, including the MyAppCustomResource CRD."
    roles:
    - type: ClusterRole
      rulesType: CUSTOM
      rules:
      - apiGroups: ['apiextensions.k8s.io']
        resources: ['customresourcedefinitions']
        verbs: ['*']
      - apiGroups: ['networking.k8s.io']
        resources: ['ingressclasses']
        verbs: ['*']
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  license.accept:
    type: string
    title: EULA License
    description: Accept EULA license
    default: 'no'
    enum:
    - 'yes'
    - 'no'
  nsIP:
    type: string
    title: NS IP of the VPX
    description: NS IP of the VPX
  nsVIP:
    type: string
    title: Virtual IP of the VPX
    description: Virtual IP of the VPX
  nsSNIPS:
    type: string
    title: Subnet IPs of the VPX
    description: The list of subnet IPAddresses on the Citrix ADC device, which will be used to create PBR Routes instead of Static Routes.
  serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: "These Permission are required for configuring Citrix ADC VPX according to the current state of the Kubernetes Cluster"
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources: ["endpoints", "pods", "secrets", "routes", "nodes", "namespaces", "configmaps","services"]
            verbs: ["get", "list", "watch"]
          - apiGroups: [""]
            resources: ["services/status"]
            verbs: ["patch"]
          - apiGroups: [""]
            resources: ["events"]
            verbs: ["create"]
          - apiGroups: ["extensions","networking.k8s.io"]
            resources: ["ingresses"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["extensions","networking.k8s.io"]
            resources: ["ingresses/status"]
            verbs: ["patch"]
          - apiGroups: ["networking.k8s.io"]
            resources: ["ingressclasses"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["apps"]
            resources: ["deployments"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["citrix.com"]
            resources: ["rewritepolicies", "continuousdeployments", "authpolicies", "ratelimits", "listeners", "httproutes", "wafs", "apigatewaypolicies", "bots", "corspolicies", "appqoepolicies"]
            verbs: ["get", "list", "watch", "create", "delete", "patch"]
          - apiGroups: ["citrix.com"]
            resources: ["rewritepolicies/status", "continuousdeployments/status", "authpolicies/status", "ratelimits/status", "listeners/status", "httproutes/status", "wafs/status", "apigatewaypolicies/status", "bots/status", "corspolicies/status", "appqoepolicies/status"]
            verbs: ["patch"]
          - apiGroups: ["citrix.com"]
            resources: ["vips"]
            verbs: ["get", "list", "watch", "create", "delete"]
          - apiGroups: ["crd.projectcalico.org"]
            resources: ["ipamblocks"]
            verbs: ["get", "list", "watch"]
  adcCredentialSecret:
    type: string
    title: Kubenetes Secret Name for Citrix ADC Credentials
    description: Kubenetes secret name created using Citrix ADC Credentials to log on to the Citrix ADC VPX or MPX.
  nsPort:
    type: integer
    title: NITRO port
    description: Port used for Citrix ADC NITRO.
    default: 443
    minimum: 0
    maximum: 65535
  nsProtocol:
    type: string
    title: Protocol for NITRO
    description: Protocol used for Citrix ADC NITRO.
    default: HTTPS
    enum:
    - "HTTPS"
    - "HTTP"
  logLevel:
    type: string
    title: Log level of Citrix ingress controller
    description: Level of logs generated by Citrix ingress controller
    default: INFO
    enum:
    - "CRITICAL"
    - "ERROR"
    - "WARNING"
    - "INFO"
    - "DEBUG"
    - "TRACE"
  entityPrefix:
    type: string
    title: Prefix
    description: The prefix for the resources on the Citrix ADC VPX/MPX.
    default: k8s
  jsonLog:
    type: boolean
    title: Log format in JSON
    description: Set this argument to True if CIC log messages are required in JSON format
    default: False
  nitroReadTimeout:
    type: integer
    title: Nitro Timeout
    description: The nitro Read timeout in seconds.
    default: 20
  clusterName:
    type: string
    title: Kubernetes cluster Identifier
    description: The unique identifier of the kubernetes cluster on which the CIC is deployed. Used in multi-cluster deployments.
  kubernetesURL:
    type: string
    title: Kubernetes URL
    description: The kube-apiserver url that CIC uses to register the events. If the value is not specified, CIC uses the internal kube-apiserver IP address.
  ingressClass:
    type: string
    title: Ingress Class
    description: Please provide name of the Ingress Class.
  setAsDefaultIngressClass:
    type: boolean
    title: Set as Default Ingress Class
    description: Set the IngressClass object as default ingress class. New Ingresses without an "ingressClassName" field specified will be assigned the class specified in ingressClass. Applicable only for Kubernetes versions >= 1.19.
    default: False
  updateIngressStatus:
    type: boolean
    title: Update Ingress Status
    description: Set this argurment if Status.LoadBalancer.Ingress field of the Ingress resources managed by the Citrix ingress controller needs to be updated with allocated IP addresses.
    default: False
  serviceClass:
    type: string
    title: Service Class
    description: By Default ingress controller configures all TypeLB Service on the ADC. You can use this parameter to finetune this behavior by specifing CIC to only configure TypeLB Service with specific service class.
  defaultSSLCertSecret:
    type: string
    title: Default SSL Certificate Secret Name
    description: Provide Kubernetes secret name that needs to be used as a default non-SNI certificate in Citrix ADC.
  podIPsforServiceGroupMembers:
    type: boolean
    title: Use Pod IPs for ServiceGroup Members
    description: By default Citrix Ingress Controller will add NodeIP and NodePort as service group members while configuring type LoadBalancer Services and NodePort services. This variable if set to 'True' will change the behaviour to add pod IP and Pod port instead of nodeIP and nodePort. Users can set this to 'True' if there is a route between ADC and K8s clusters internal pods either using feature-node-watch argument or using Citrix Node Controller.
    default: False
  ignoreNodeExternalIP:
    type: boolean
    title: Use Node Internal IPs
    description: If this variable is set to 'True', then Citrix Ingress Controller prioritises the Node Internal IP to be used for service group members even if node ExternalIP is present.
    default: False
  disableAPIServerCertVerify:
    type: boolean
    title: Disable API Server Cert Verification
    description: Set this parameter to True for disabling API Server certificate verification.
    default: False
  ipam:
    type: boolean
    title: Using IPAM Controller?
    description: Set this argument if you want to use the IPAM controller to automatically allocate an IP address to the service of type LoadBalancer.
    default: False
  nodeWatch:
    type: boolean
    title: Automatic static route configuration
    description: Automatic static route configuration on Citrix ADC VPX towards the pod network.
    default: False
  nodeSelector.key:
    type: string
    title: Provide Node Selector Key for CIC
    description: Node label key to be used for nodeSelector option in CIC deployment.
  nodeSelector.value:
    type: string
    title: Provide Node Selector Value for CIC
    description: Node label value to be used for nodeSelector option in CIC deployment.
  nsHTTP2ServerSide:
    type: string
    title: HTTP2 for Citrix ADC service group
    description: Set this argument to ON for enabling HTTP2 for Citrix ADC service group configurations.
    default: 'OFF'
    enum:
    - 'OFF'
    - 'ON'
  nsCookieVersion:
    type: string
    title: Persistence Cookie Version
    description: Specify the persistence cookie version.
    default: '0'
    enum:
    - '0'
    - '1'
  nsConfigDnsRec:
    type: boolean
    title: Enable DNS address record addition through ingress.
    description: Set to True to enable DNS address Record addition in ADC through Ingress.
    default: False
  nsSvcLbDnsRec:
    type: boolean
    title:  Enable DNS address record addition through service type LB.
    description: Set to True to enable DNS address Record addition in ADC through Type Load Balancer Service
    default: False
  nsDnsNameserver:
    type: string
    title: DNS Nameservers
    description: To add DNS Nameservers in ADC
  exporter.required:
    type: boolean
    title: Prometheus Exporter required?
    description: Set if exporter is needed with Citrix ADC VPX.
    default: False
  exporter.ports.containerPort:
    type: integer
    title: Prometheus Exporter Port
    description: Specify on which port metrics collected by the exporter should be exposed.
    default: 8888
    minimum: 0
    maximum: 65535
  crd.install:
    type: boolean
    title: Install CRDs provided by Citrix
    description: Unset this argument if you don't want to install CustomResourceDefinitions which are consumed by CIC.
    default: True
  crds.retainOnDelete:
    type: boolean
    title: Retain CRDs on delete
    description: Set this argument if you want to retain CustomResourceDefinitions even after uninstalling CIC. This will avoid data-loss of Custom Resource Objects created before uninstallation.
    default: False
  coeConfig.required:
    type: boolean
    title: COE Config Required?
    description: Set this to True if you want to configure Citrix ADC to send metrics and transaction records to COE.
    default: False
  coeConfig.distributedTracing.enable:
    type: boolean
    title: Enable OpenTracing in Citrix ADC.
    description: Set this value to True to enable OpenTracing in Citrix ADC.
    default: False
  coeConfig.distributedTracing.samplingrate:
    type: integer
    title: OpenTracing sampling rate in percentage.
    description: Specifies the OpenTracing sampling rate in percentage.
    default: 100
    minimum: 0
    maximum: 100
  coeConfig.endpoint.server:
    type: string
    title: IP address or DNS address of the analytics server.
    description: Set this value as the IP address or DNS address of the analytics server.
  coeConfig.endpoint.service:
    type: string
    title: IP address or DNS address of the analytics service in Kubernetes.
    description: Set this value as the IP address or service name with namespace of the analytics service deployed in k8s environment. Format is "namespace/servicename".
  coeConfig.timeseries.port:
    type: integer
    title: Port used to expose COE service for timeseries endpoint.
    description: Specify the port used to expose COE service outside cluster for timeseries endpoint.
    default: 30002
    minimum: 0
    maximum: 65535
  coeConfig.timeseries.metrics.enable:
    type: boolean
    title: Enable sending metrics from Citrix ADC.
    description: Set this value to True to enable sending metrics from Citrix ADC.
    default: False
  coeConfig.timeseries.metrics.mode:
    type: string
    title: Specifies the mode of metric endpoint.
    description: Specifies the mode of metric endpoint.
    default: avro
  coeConfig.timeseries.auditlogs.enable:
    type: boolean
    title: Export audit log data from Citrix ADC
    description: Set this value to True to export audit log data from Citrix ADC.
    default: False
  coeConfig.timeseries.events.enable:
    type: boolean
    title: Export events from the Citrix ADC
    description: Set this value to True to export events from the Citrix ADC.
    default: False
  coeConfig.transactions.enable:
    type: boolean
    title: Export transactions from Citrix ADC.
    description: Set this value to True to export transactions from Citrix ADC.
    default: False
  coeConfig.transactions.port:
    type: integer
    title: Port used to expose COE service for transaction endpoint.
    description: Specify the port used to expose COE service outside cluster for transaction endpoint.
    default: 30001
    minimum: 0
    maximum: 65535
  nsLbHashAlgo.required:
    type: boolean
    title: Enable LB consistent hashing algorithm
    description: Set this value to enable the LB consistent hashing Algorithm
    default: False
  nsLbHashlgo.hashFingers:
    type: integer
    title: Number of fingers for Hash
    description: Specify the number of fingers to be used for hashing algorithm.
    default: 256
    minimum: 1
    maximum: 1024
  nsLbHashAlgo.hashAlgorithm:
    type: string
    title: Hash Algorithm
    description: Specifies the supported hashing algorithm.
    default: 'DEFAULT'
    enum:
    - 'DEFAULT'
    - 'JARH'
    - 'PRAC'
  appUid:
    type: string
    x-google-marketplace:
      type: APPLICATION_UID
      applicationUid:
        generatedProperties:
          createApplicationBoolean: global.application.create
required:
- name
- namespace
- serviceAccount
- nsIP
- adcCredentialSecret
- exporter.required
- coeConfig.required
